import { Routes, Route } from "react-router-dom";
import NoticeDashboard from "./pages/NoticeDashboard";
import GenerateNotice from "./pages/GenerateNotice";
import CitizenNoticeView from "./pages/CitizenNoticeView";

function NoticeRoutes() {
  return (
    <Routes>
      <Route path="/" element={<NoticeDashboard />} />
      <Route path="generate" element={<GenerateNotice />} />
      <Route
        path="view"
        element={
          <CitizenNoticeView
            noticeHtml={`
    <address>
      <strong>Jane Doe</strong><br/>
      123 Main Street, Anytown, USA 12345
    </address>
    <h3>Notice of Eligibility for Health Insurance System Benefits</h3>
    <p>Dear Jane Doe,</p>
    <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p> <p>
      This letter is to inform you of the decision regarding your application...
    </p>
  `}
            onBack={() => console.log("Go back")}
            onPrint={() => window.print()}
            onDownload={() => console.log("Download PDF")}
          />
        }
      />
    </Routes>
  );
}

export default NoticeRoutes;
